name: React Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: yarn install
      - name: Build file
        run: yarn build
      - name: Run lint
        run: yarn lint
