name: React Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: yarn install
      - name: Build file
        run: yarn build
      - name: Run lint
        run: yarn lint
